import type { ControlRoomCopy } from './types';

export const EN_CONTROL_ROOM_COPY = {
  common: {
    no: 'no',
    off: 'off',
    on: 'on',
    yes: 'yes',
    working: 'Working...',
  },
  auth: {
    body: 'Enter the Web GUI token from your ignored local environment. The token is exchanged for a same-origin HttpOnly session cookie and is not rendered into the page.',
    eyebrow: 'Protected local command center',
    title: 'Agentic Trader',
    tokenLabel: 'Web GUI token',
    unlock: 'Unlock',
    unlocking: 'Unlocking...',
  },
  hero: {
    alt: 'Trading screens showing market data.',
    copy: 'Local-first runtime, paper-first execution, and the same dashboard contract that powers CLI, Rich, and Ink.',
    eyebrow: 'Operator Truth',
    sessionUnknown: 'session unknown',
    title: 'Agentic Trader Web GUI',
  },
  feedback: {
    dashboardRefreshed: 'Dashboard refreshed.',
    instructionPreviewReady: 'Instruction preview ready.',
    operatorReplyReceived: 'Operator reply received.',
    preferencesUpdated: 'Preferences updated from operator instruction.',
  },
  chat: {
    empty: 'No chat messages yet.',
    panels: {
      decisionWorkflowContext: 'Decision Workflow Context',
      operatorChat: 'Operator Chat',
    },
    placeholder: 'Ask for a review, status, or explanation.',
    role: 'Role',
    send: 'Send',
    userLabel: 'you',
    workflow: {
      completedDetail: 'Completed Detail',
      currentStage: 'Current Stage',
      lastCompleted: 'Last Completed',
      memoryRoles: 'Memory Roles',
      stageDetail: 'Stage Detail',
      stageStatus: 'Stage Status',
      toolRoles: 'Tool Roles',
    },
  },
  currentCycle: {
    cycleCount: 'Cycle Count',
    currentStage: 'Current Stage',
    currentSymbol: 'Current Symbol',
    lastOutcome: 'Last Outcome',
    mode: 'Mode',
    runtime: 'Runtime',
    stageStatus: 'Stage Status',
    status: 'Status',
    waitingOutcome: 'Waiting for a completed symbol or service result.',
  },
  overview: {
    emptyStageEvents: 'No live agent stage events yet.',
    panels: {
      currentCycle: 'Current Cycle',
      decisionWorkflow: 'Decision Workflow',
      localTools: 'Local Tools',
      providerWarnings: 'Provider Warnings',
      readinessGates: 'Readiness Gates',
      system: 'System',
    },
    tools: {
      appTools: 'App Tools',
      camofox: 'Camofox',
      hostFallback: 'Host Fallback',
      ollama: 'Ollama',
    },
  },
  memory: {
    emptyRetrieval: 'No retrieval inspection data available yet.',
    emptySimilar: 'No similar historical memories found yet.',
    labels: {
      memoryExplorer: 'Memory explorer',
      noRetrievalContext: 'No retrieval context attached.',
      retrievalInspection: 'Retrieval inspection',
      sample: 'Sample',
      why: 'Why',
    },
    panels: {
      similarPastRuns: 'Similar Past Runs',
      whyContextWasUsed: 'Why This Context Was Used',
    },
  },
  portfolio: {
    emptyTradeJournal: 'No trade journal entries yet.',
    fields: {
      behavior: 'Behavior',
      basisPoints: 'bps',
      cash: 'Cash',
      currencies: 'Currencies',
      currency: 'Currency',
      deskFees: 'Fees',
      drawdown: 'Drawdown',
      equity: 'Equity',
      exchanges: 'Exchanges',
      generatedAt: 'Generated At',
      grossExposure: 'Gross Exposure',
      largestPosition: 'Largest Position',
      markSource: 'Mark Source',
      markStatus: 'Mark Status',
      markedAt: 'Marked At',
      marketValue: 'Market Value',
      openPositions: 'Open Positions',
      paperMark: 'paper mark',
      realizedPnl: 'Realized PnL',
      regions: 'Regions',
      rejectionEvidence: 'Rejection Evidence',
      risk: 'Risk',
      sectors: 'Sectors',
      slippage: 'Slippage',
      strictness: 'Strictness',
      style: 'Style',
      tone: 'Tone',
      unrealizedPnl: 'Unrealized PnL',
      warnings: 'Warnings',
    },
    noWarnings: 'No warnings.',
    panels: {
      deskAccountingNotes: 'Desk Accounting Notes',
      exitPlanCoverage: 'Exit Plan Coverage',
      portfolio: 'Portfolio',
      preferences: 'Preferences',
      riskReport: 'Risk Report',
      tradeJournal: 'Trade Journal',
    },
    unavailable: {
      portfolio: 'Portfolio',
      riskReport: 'Risk report',
      tradeJournal: 'Trade journal',
    },
  },
  proposals: {
    actions: {
      approve: {
        label: 'Approve',
        title: 'Approve pending paper proposal',
      },
      reject: {
        label: 'Reject',
        title: 'Reject pending proposal',
      },
      reconcile: {
        label: 'Reconcile',
        title: 'Reconcile approved in-flight proposal',
      },
      refresh: {
        label: 'Refresh',
        title: 'Refresh accepted broker order without resubmitting',
      },
    },
    fields: {
      backend: 'Backend',
      externalPaper: 'External Paper',
      killSwitch: 'Kill Switch',
      liveRequested: 'Live Requested',
      message: 'Message',
      state: 'State',
    },
    notePlaceholder:
      'Review note required for approve, reject, reconcile, or refresh.',
    panels: {
      deskSafety: 'Desk Safety',
      proposalDesk: 'Proposal Desk',
    },
    stopTake: (stop, take) => `stop ${stop} / take ${take}`,
  },
  review: {
    emptyPersistedRuns: 'No persisted runs are available yet.',
    fields: {
      approved: 'Approved',
      consensus: 'Consensus',
      coordinatorFocus: 'Coordinator Focus',
      created: 'Created',
      reviewSummary: 'Review Summary',
      runId: 'Run ID',
      symbol: 'Symbol',
    },
    panels: {
      canonicalAnalysis: 'Canonical Analysis',
      latestReview: 'Latest Review',
      marketContextPack: 'Market Context Pack',
      tradeContext: 'Trade Context',
    },
    unavailable: {
      latestReview: 'Latest review',
    },
  },
  runtime: {
    empty: {
      events: 'No runtime events recorded yet.',
      stderr: 'No stderr tail.',
      stdout: 'No stdout tail.',
    },
    fields: {
      currentSymbol: 'Current Symbol',
      cycleCount: 'Cycle Count',
      liveProcess: 'Live Process',
      pid: 'PID',
      runtime: 'Runtime',
      status: 'Status',
      stopRequested: 'Stop Requested',
      updated: 'Updated',
    },
    panels: {
      events: 'Runtime Events',
      stageFlow: 'Stage Flow',
      state: 'Runtime State',
      supervisorTails: 'Supervisor Tails',
    },
  },
  settings: {
    actions: {
      apply: 'Apply',
      preview: 'Preview',
    },
    examples: [
      'make the system conservative',
      'switch to capital preservation',
    ],
    fields: {
      agentProfile: 'Profile',
      applied: 'Applied',
      approved: 'Approved',
      behavior: 'Behavior',
      currencies: 'Currencies',
      exchanges: 'Exchanges',
      instructionExamples: 'Examples:',
      instructionRationale: 'Rationale',
      instructionSummary: 'Summary',
      mode: 'Mode',
      regions: 'Regions',
      requiresConfirmation: 'Requires Confirmation',
      risk: 'Risk',
      sectors: 'Sectors',
      shouldUpdatePreferences: 'Update Preferences',
      strictness: 'Strictness',
      style: 'Style',
      tone: 'Tone',
    },
    instructionEmpty: 'Type a safe operator instruction.',
    modeOptions: {
      apply: 'apply',
      preview: 'preview',
    },
    panels: {
      composer: 'Composer',
      operatorInstruction: 'Operator Instruction',
      preferences: 'Preferences',
      recentRuns: 'Recent Runs',
    },
    placeholder: 'Make the system more conservative and protective.',
    recentRunsEmpty: 'No recent runs recorded yet.',
  },
  shell: {
    actions: {
      oneShot: 'One Shot',
      refresh: 'Refresh',
      restart: 'Restart',
      start: 'Start',
      stop: 'Stop',
    },
    backend: 'Backend',
    eyebrow: 'Local-first control room',
    language: 'Language',
    lastRefresh: 'Last refresh',
    loading: 'Loading dashboard...',
    mode: 'Mode',
    navAria: 'Sections',
    runtime: 'Runtime',
    runtimeUnavailable: 'runtime unavailable',
    subtitle: 'Paper-first. Strict. Inspectable.',
    title: 'Agentic Trader',
    unavailable: 'Dashboard unavailable.',
  },
  tabs: {
    overview: 'Overview',
    runtime: 'Runtime',
    portfolio: 'Portfolio',
    proposals: 'Proposals',
    review: 'Review',
    memory: 'Decision Evidence',
    chat: 'Chat',
    settings: 'Settings',
  },
} satisfies ControlRoomCopy;
