import type { ControlRoomCopy } from './types';

export const TR_CONTROL_ROOM_COPY = {
  common: {
    no: 'hayır',
    off: 'kapalı',
    on: 'açık',
    yes: 'evet',
    working: 'Çalışıyor...',
  },
  auth: {
    body: 'Yerel ortamdaki Web GUI token bilgisini gir. Token aynı origin üzerinde HttpOnly oturum çerezine çevrilir ve sayfada gösterilmez.',
    eyebrow: 'Korumalı yerel komut merkezi',
    title: 'Agentic Trader',
    tokenLabel: 'Web GUI token',
    unlock: 'Kilidi aç',
    unlocking: 'Kilit açılıyor...',
  },
  hero: {
    alt: 'Piyasa verilerini gösteren işlem ekranları.',
    copy: 'Yerel-öncelikli runtime, paper-first işlem ve CLI, Rich, Ink yüzeylerini besleyen aynı dashboard sözleşmesi.',
    eyebrow: 'Operatör gerçeği',
    sessionUnknown: 'seans bilinmiyor',
    title: 'Agentic Trader Web GUI',
  },
  feedback: {
    dashboardRefreshed: 'Dashboard yenilendi.',
    instructionPreviewReady: 'Talimat önizlemesi hazır.',
    operatorReplyReceived: 'Operatör yanıtı alındı.',
    preferencesUpdated: 'Tercihler operatör talimatından güncellendi.',
  },
  chat: {
    empty: 'Henüz chat mesajı yok.',
    panels: {
      decisionWorkflowContext: 'Karar Akışı Bağlamı',
      operatorChat: 'Operatör Chat',
    },
    placeholder: 'İnceleme, durum veya açıklama iste.',
    role: 'Rol',
    send: 'Gönder',
    userLabel: 'sen',
    workflow: {
      completedDetail: 'Tamamlanan Detay',
      currentStage: 'Güncel Aşama',
      lastCompleted: 'Son Tamamlanan',
      memoryRoles: 'Bellek Rolleri',
      stageDetail: 'Aşama Detayı',
      stageStatus: 'Aşama Durumu',
      toolRoles: 'Araç Rolleri',
    },
  },
  currentCycle: {
    cycleCount: 'Cycle Sayısı',
    currentStage: 'Güncel Aşama',
    currentSymbol: 'Güncel Sembol',
    lastOutcome: 'Son Sonuç',
    mode: 'Mod',
    runtime: 'Runtime',
    stageStatus: 'Aşama Durumu',
    status: 'Durum',
    waitingOutcome: 'Tamamlanmış sembol veya servis sonucu bekleniyor.',
  },
  overview: {
    emptyStageEvents: 'Henüz canlı ajan aşama olayı yok.',
    panels: {
      currentCycle: 'Güncel Cycle',
      decisionWorkflow: 'Karar Akışı',
      localTools: 'Yerel Araçlar',
      providerWarnings: 'Provider Uyarıları',
      readinessGates: 'Hazırlık Kapıları',
      system: 'Sistem',
    },
    tools: {
      appTools: 'App Araçları',
      camofox: 'Camofox',
      hostFallback: 'Host Yedeği',
      ollama: 'Ollama',
    },
  },
  memory: {
    emptyRetrieval: 'Henüz retrieval inceleme verisi yok.',
    emptySimilar: 'Henüz benzer geçmiş bellek bulunmadı.',
    labels: {
      memoryExplorer: 'Bellek gezgini',
      noRetrievalContext: 'Retrieval bağlamı eklenmemiş.',
      retrievalInspection: 'Retrieval incelemesi',
      sample: 'Örnek',
      why: 'Neden',
    },
    panels: {
      similarPastRuns: 'Benzer Geçmiş Runlar',
      whyContextWasUsed: 'Bu Bağlam Neden Kullanıldı',
    },
  },
  portfolio: {
    emptyTradeJournal: 'Henüz işlem günlüğü kaydı yok.',
    fields: {
      behavior: 'Davranış',
      basisPoints: 'bps',
      cash: 'Nakit',
      currencies: 'Para Birimleri',
      currency: 'Para Birimi',
      deskFees: 'Ücretler',
      drawdown: 'Drawdown',
      equity: 'Equity',
      exchanges: 'Borsalar',
      generatedAt: 'Üretilme Zamanı',
      grossExposure: 'Brüt Maruziyet',
      largestPosition: 'En Büyük Pozisyon',
      markSource: 'Mark Kaynağı',
      markStatus: 'Mark Durumu',
      markedAt: 'Mark Zamanı',
      marketValue: 'Piyasa Değeri',
      openPositions: 'Açık Pozisyonlar',
      paperMark: 'paper mark',
      realizedPnl: 'Realized PnL',
      regions: 'Bölgeler',
      rejectionEvidence: 'Red Kanıtı',
      risk: 'Risk',
      sectors: 'Sektörler',
      slippage: 'Slippage',
      strictness: 'Katılık',
      style: 'Stil',
      tone: 'Ton',
      unrealizedPnl: 'Unrealized PnL',
      warnings: 'Uyarılar',
    },
    noWarnings: 'Uyarı yok.',
    panels: {
      deskAccountingNotes: 'Desk Muhasebe Notları',
      exitPlanCoverage: 'Exit Plan Kapsamı',
      portfolio: 'Portföy',
      preferences: 'Tercihler',
      riskReport: 'Risk Raporu',
      tradeJournal: 'İşlem Günlüğü',
    },
    unavailable: {
      portfolio: 'Portföy',
      riskReport: 'Risk raporu',
      tradeJournal: 'İşlem günlüğü',
    },
  },
  proposals: {
    actions: {
      approve: {
        label: 'Onayla',
        title: 'Bekleyen paper teklifi onayla',
      },
      reject: {
        label: 'Reddet',
        title: 'Bekleyen teklifi reddet',
      },
      reconcile: {
        label: 'Eşle',
        title: 'Onaylı in-flight teklifi broker durumu ile eşle',
      },
      refresh: {
        label: 'Yenile',
        title: 'Kabul edilmiş broker emrini yeniden göndermeden yenile',
      },
    },
    fields: {
      backend: 'Backend',
      externalPaper: 'External Paper',
      killSwitch: 'Kill Switch',
      liveRequested: 'Live İstendi',
      message: 'Mesaj',
      state: 'Durum',
    },
    notePlaceholder:
      'Onay, red, eşleme veya yenileme için inceleme notu gerekli.',
    panels: {
      deskSafety: 'Desk Güvenliği',
      proposalDesk: 'Teklif Masası',
    },
    stopTake: (stop, take) => `stop ${stop} / take ${take}`,
  },
  review: {
    emptyPersistedRuns: 'Henüz kalıcı run yok.',
    fields: {
      approved: 'Onaylı',
      consensus: 'Konsensüs',
      coordinatorFocus: 'Koordinatör Odağı',
      created: 'Oluşturuldu',
      reviewSummary: 'İnceleme Özeti',
      runId: 'Run ID',
      symbol: 'Sembol',
    },
    panels: {
      canonicalAnalysis: 'Canonical Analiz',
      latestReview: 'Son İnceleme',
      marketContextPack: 'Piyasa Bağlam Paketi',
      tradeContext: 'İşlem Bağlamı',
    },
    unavailable: {
      latestReview: 'Son inceleme',
    },
  },
  runtime: {
    empty: {
      events: 'Henüz runtime olayı yok.',
      stderr: 'Stderr tail yok.',
      stdout: 'Stdout tail yok.',
    },
    fields: {
      currentSymbol: 'Güncel Sembol',
      cycleCount: 'Cycle Sayısı',
      liveProcess: 'Canlı Process',
      pid: 'PID',
      runtime: 'Runtime',
      status: 'Durum',
      stopRequested: 'Durdurma İsteği',
      updated: 'Güncellendi',
    },
    panels: {
      events: 'Runtime Olayları',
      stageFlow: 'Aşama Akışı',
      state: 'Runtime Durumu',
      supervisorTails: 'Supervisor Tail',
    },
  },
  settings: {
    actions: {
      apply: 'Uygula',
      preview: 'Önizle',
    },
    examples: ['sistemi daha konservatif yap', 'sermaye korumaya geç'],
    fields: {
      agentProfile: 'Profil',
      applied: 'Uygulandı',
      approved: 'Onaylı',
      behavior: 'Davranış',
      currencies: 'Para Birimleri',
      exchanges: 'Borsalar',
      instructionExamples: 'Örnekler:',
      instructionRationale: 'Gerekçe',
      instructionSummary: 'Özet',
      mode: 'Mod',
      regions: 'Bölgeler',
      requiresConfirmation: 'Onay Gerektirir',
      risk: 'Risk',
      sectors: 'Sektörler',
      shouldUpdatePreferences: 'Tercihleri Güncelle',
      strictness: 'Katılık',
      style: 'Stil',
      tone: 'Ton',
    },
    instructionEmpty: 'Güvenli bir operatör talimatı yaz.',
    modeOptions: {
      apply: 'uygula',
      preview: 'önizle',
    },
    panels: {
      composer: 'Composer',
      operatorInstruction: 'Operatör Talimatı',
      preferences: 'Tercihler',
      recentRuns: 'Son Runlar',
    },
    placeholder: 'Sistemi daha konservatif ve korumacı yap.',
    recentRunsEmpty: 'Henüz kayıtlı run yok.',
  },
  shell: {
    actions: {
      oneShot: 'Tek Cycle',
      refresh: 'Yenile',
      restart: 'Yeniden Başlat',
      start: 'Başlat',
      stop: 'Durdur',
    },
    backend: 'Backend',
    eyebrow: 'Yerel-öncelikli kontrol odası',
    language: 'Dil',
    lastRefresh: 'Son yenileme',
    loading: 'Dashboard yükleniyor...',
    mode: 'Mod',
    navAria: 'Bölümler',
    runtime: 'Runtime',
    runtimeUnavailable: 'runtime kullanılamıyor',
    subtitle: 'Paper-first. Katı. Denetlenebilir.',
    title: 'Agentic Trader',
    unavailable: 'Dashboard kullanılamıyor.',
  },
  tabs: {
    overview: 'Özet',
    runtime: 'Runtime',
    portfolio: 'Portföy',
    proposals: 'Teklifler',
    review: 'İnceleme',
    memory: 'Karar Kanıtı',
    chat: 'Chat',
    settings: 'Ayarlar',
  },
} satisfies ControlRoomCopy;
